name: Build and Deploy

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: write  # Needed to push to gh-pages

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build Jekyll site
        run: bundle exec jekyll b
        env:
          JEKYLL_ENV: production

      - name: Test site with HTMLProofer
        run: bundle exec htmlproofer _site --disable-external --check-html --allow_hash_href

      - name: Setup Git for deploy
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Deploy to gh-pages branch
        run: |
          git fetch origin
          git switch --orphan gh-pages || git checkout gh-pages
          git reset --hard
          rm -rf *
          cp -r _site/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy site" || echo "No changes to commit"
          git push --force origin gh-pages
