name: Build and Deploy

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build Jekyll site
        run: bundle exec jekyll b
        env:
          JEKYLL_ENV: production

      - name: Test site with HTMLProofer
        run: bundle exec htmlproofer _site --disable-external --check-html --allow_hash_href

      - name: Upload artifact (no symlinks, rsync copy)
        run: |
          mkdir _site_clean
          rsync -a --copy-links --safe-links \
            --exclude '.git' \
            --exclude 'vendor' \
            _site/ _site_clean/
        shell: bash

      - name: Debug: Check for symlinks and size
        run: |
          echo "Listing all symbolic links:"
          find _site_clean -type l

          echo "Checking total size:"
          du -sh _site_clean
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _site_clean


  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
